import { Inter } from 'next/font/google'
import './globals.css'
import Header from '@/components/Header'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'linkin_park-in_the_end.mp3.exe',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`bg-[#f3f3f3] ${inter.className}`}>
        <Header/>
        {children}
      </body>
    </html>
  )
}
